name: Setup Repository

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make install-bun.sh executable
        run: chmod +x .devcontainer/install-bun.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: make install-bun.sh executable'
          commit_user_name: 'GitHub Action'
          commit_user_email: 'actions@github.com'
          commit_author: 'GitHub Action <actions@github.com>'
          push_options: '--force'
